myjeweler/myjeweler/apps/employees/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('myjeweler.apps.employees.views',
    url(r'^$', 'employees_group_view', name ='employees_group_view'),
    url(r'^employees_group_list/(?P<id>\d+)/$', 'employees_group_list', name = 'employees_group_list'),
    url(r'^(?P<id>\d+)/$', 'employee_one', name = 'employee_one'),
    url(r'^employees_list/$', 'employees_list', name ='employees_list'),
)

myjeweler/myjeweler/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()


urlpatterns = patterns('',
	url(r'^$', 'myjeweler.views.index', name='index'),
	url(r'^rings/$', 'myjeweler.views.rings', name='rings'),
	url(r'^earrings/$', 'myjeweler.views.earrings', name='earrings'),
	url(r'^pendants/$', 'myjeweler.views.pendants', name='pendants'),
    url(r'^rings/photo_rings1/$', 'myjeweler.views.photo_rings1', name='photo1'),
    url(r'^earrings/photo_earrings1/$', 'myjeweler.views.photo_earrings1', name='photo_earrings1'),

    url(r'^feedback/$', 'myjeweler.views.feedback_view', name='feedback'),


    url(r'^create/$', 'myjeweler.apps.employees.views.create_view', name='create'),
    url(r'^edit/(?P<id>\d+)/$', 'myjeweler.apps.employees.views.create_view', name='edit'),

    url(r'^employees_group_view/', include('myjeweler.apps.employees.urls')),

    url(r'^accounts/login_view/$', 'myjeweler.apps.employees.views.login_view', name="login_view"),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^accounts/logout/$', 'myjeweler.apps.employees.views.logout_view', name="logout"),

    url(r'^accounts/', include('registration.backends.default.urls')),

    url(r'^comments/', include('django.contrib.comments.urls')),


    # Examples:
    # url(r'^$', 'myjeweler.views.home', name='home'),
    # url(r'^myjeweler/', include('myjeweler.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

myjeweler/myjeweler/apps/employees/models.py
from django.db import models

class Group(models.Model):

	name = models.CharField(max_length = 30)

	def __unicode__(self):
		return self.name

class Employee(models.Model):

	group = models.ForeignKey(Group)
	first_name = models.CharField(max_length = 30)
	last_name = models.CharField(max_length = 30)

	skype = models.CharField(max_length = 255, blank = True, null = True)
	email = models.EmailField(max_length = 255, blank = True, null = True)
	github = models.URLField(max_length = 255, blank = True, null = True)
	cell = models.CharField(max_length = 15, blank = True, null = True)

	def __unicode__(self):
		return " %s %s" % (self.first_name, self.last_name)

myjeweler/myjeweler/apps/silver_adornment/models.py
from django.db import models
# -*- coding: utf-8 -*-

# class Sex(models.Model):

# 	name = models.CharField(max_length = 20)

# 	def __unicode__(self):
# 		return self.name


class SilverRings(models.Model):

	SEX = (
		(u'Мужское', 'Men'),
		(u'Женское', 'Woman'),
		(u'Унисекс', 'Unisex'),
		)
	image = models.ImageField(upload_to = 'rings', blank = True, null = True)
	name = models.CharField(max_length = 50)
	art = models.CharField(max_length = 50)
	weigth = models.CharField(max_length = 50)
	sex = models.CharField(max_length = 10, choices = SEX)

	class Meta:
		verbose_name = 'SilverRing'
		verbose_name_plural = 'SilverRings'

	def __unicode__(self):
		return self.name


class TypeEarrings(models.Model):

	name = models.CharField(max_length = 50)

	class Meta:
		verbose_name = 'TypeEarring'
		verbose_name_plural = 'TypeEarrings'

	def __unicode__(self):
		return self.name


class SilverEarrings(models.Model):

	type_earrings = models.ForeignKey(TypeEarrings)
	image = models.FileField(upload_to = 'earrings', blank = True, null = True)
	name = models.CharField(max_length = 50)
	art = models.CharField(max_length = 50)
	weigth = models.CharField(max_length = 50)

	class Meta:
		verbose_name = 'SilverEarring'
		verbose_name_plural = 'SilverEarrings'

	def __unicode__(self):
		return self.name


class TypePendants(models.Model):

	name = models.CharField(max_length = 50)

	class Meta:
		verbose_name = 'TypePendant'
		verbose_name_plural = 'TypePendants'

	def __unicode__(self):
		return self.name


class Pendants(models.Model):

	type_pendants = models.OneToOneField(TypePendants)
	image = models.ImageField(upload_to = 'pendants', blank = True, null = True)
	name = models.CharField(max_length = 50)
	art = models.CharField(max_length = 50)
	weigth = models.CharField(max_length = 50)

	class Meta:
		verbose_name = 'Pendant'
		verbose_name_plural = 'Pendants'

	def __unicode__(self):
		return self.name

myjeweler/myjeweler/apps/employees/views.py
# -*- coding: utf-8 -*-

from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, redirect
from myjeweler.apps.employees.models import Group, Employee
from django.forms import ModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout,login, authenticate



class GroupForm(ModelForm):

	class Meta:
		model = Group

@login_required
def employees_group_view(request):

	groups = Group.objects.all()
	form = GroupForm(request.GET)
	if form.is_valid():
			groups = form.save()
			return redirect(reverse('employees_group_view'))
	else:
		form = GroupForm()
	return render(request, "employees.html",
					{'groups': groups,
					'form': form })

@login_required
def employees_group_list(request, id):
	group = get_object_or_404(Group, id=id)
	employees = Employee.objects.filter(group = group)
	return render(request, "employees_item.html",
		{'employees': employees,
		'group': group})

@login_required
def employee_one(request, id):
	employee = get_object_or_404(Employee, id=id)
	return render(request, "employee_one.html",
				{'employee': employee})

@login_required
def	employees_list(request):
	items = Employee.objects.all()
	return render(request, 'employees_list.html',
				{'items': items})


class EmployeeForm(ModelForm):

	class Meta:
		model = Employee
		
@login_required
def create_view(request, id=None):
	if id is not None:
		employee = get_object_or_404(Employee,id=id)
	else:
		employee = None

	if request.GET:
		form = EmployeeForm(request.GET, instance=employee)
		if form.is_valid():
			employee = form.save()
			return redirect(reverse('employee_one', args=[employee.id]))
	else:
		form = EmployeeForm(instance=employee)

	return render(request,'employee_create.html',{
					'form': form, 'employee': employee})


def login_view(login):
	return redirect(reverse('login') + '?next=%s' % reverse('index'))

def logout_view(request):
	logout(request)
	return redirect(reverse('index'))

def login_view_test(request):
	pass

myjeweler/myjeweler/views.py
# -*- coding: utf-8 -*-
from datetime import datetime 


from django.contrib import messages
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from myjeweler.apps.silver_adornment.models import SilverRings, SilverEarrings, TypeEarrings
from django import forms
from django.core.mail import send_mail
from django.template.loader import render_to_string

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
	return render(request, "index.html")

def rings(request):
	rings = SilverRings.objects.all()
	return render(request, "rings.html", {
		'rings': rings
		})


class ContactForm(forms.Form):
	name = forms.CharField()
	email = forms.EmailField()
	text = forms.CharField(widget=forms.Textarea)


def feedback_view(request):

	if request.method == "POST":
		form = ContactForm(request.POST)
		if form.is_valid():			
			data = form.cleaned_data
			data['date'] = datetime.now()
			message = render_to_string('my_feedback.txt', data)
			send_mail("Message form from Myjewelry", message, data['email'], ["sendr84@gmail.com"] )
			messages.success(request, u'Сообщение было успешно отправлено')
			return redirect(reverse("feedback"))
	else:
		form = ContactForm()
	return render(request, "feedback.html",{
						'form': form})

def earrings(request):
	earrings = SilverEarrings.objects.all()
	paginator = Paginator(earrings, 5)
	page = request.GET.get('page', 1)
	try:
		earrings = paginator.page(page)
	except (PageNotAnInteger, EmptyPage):
		raise Http404
	return render(request, "earrings.html", {
		'earrings': earrings,
		'next': reverse('earrings')
		})


def pendants(request):
	return render(request, "pendants.html")

def photo_rings1(request):
	return render(request, "photo_rings1.html")

def photo_earrings1(request):
	return render(request, "photo_earrings1.html")

def photo1(request):
	return render(request, "photo1.html")
	

myjeweler/myjeweler/templates/earrings.html
{% extends "base.html" %}

{% block earrings_class %} class="active" {% endblock %}

{% block earrings_class_ %} class="active" {% endblock %}

{% load comments %}


{% block content %}
				

			<div>
				<ul>
					<div class="pagination">
    					<span class="step-links">
        					{% if earrings.has_previous %}
            				<a href="?page={{ earrings.previous_page_number }}">previous</a>
        					{% endif %}

        					<span class="current">
            					Page {{ earrings.number }} of {{ earrings.paginator.num_pages }}.
        					</span>

        					{% if earrings.has_next %}
            				<a href="?page={{ earrings.next_page_number }}">next</a>
        					{% endif %}
    					</span>
					</div>
	
					{% for earring in earrings %}
					<li>
						<table cellpadding="3" style="border: 1px solid; width:400px; margin:0 0 10px">
							<tr>
								<td>Фото:</td>
								<td>Название:</td>
								<td>Пол:</td>
								<td>Вес:</td>
							</tr>
							<tr>	
								<td><img src="{{ earring.image.url }}" class = "image_ring"></td>
								<td>{{earring.name}}</td>
								<td>{{earring.type_earrings }}</td>
								<td>{{ earring.weigth }}</td>
							</tr>
							<tr>
							</tr>
								<td>
									<div id="accordion">
  										<h3>Комментарий</h3>
												  <div>
												    <!-- <p> -->
												    	{% get_comment_form for earring as form %}
														{% include "comments/form.html" %}

														{% get_comment_list for earring as comment_list %}
													<!-- </p> -->
												  </div>
														{% for comment in comment_list %}
														{{ comment.user_name }}: {{ comment.comment }}

														{% endfor %}
									<!-- <div>{% get_comment_form for earring as form %}
						{% include "comments/form.html" %}

									{% get_comment_list for earring as comment_list %}
									{% for comment in comment_list %}
									{{ comment.user_name }}: {{ comment.comment }}

									{% endfor %}
									</div> -->
								</td>
						</table>
						<!-- <table>
						  <form action="{% comment_form_target %}" method="post">
						    {% csrf_token %}
						    {{ form }}
						    <tr>
						      <td colspan="2">
						        <input type="submit" name="submit" value="Post">
						        <input type="submit" name="preview" value="Preview">
						      </td>
						    </tr>
						  </form>
						</table> -->
					</li>
					{% endfor %}
				</ul>	
			</div>
{% endblock content %}

myjeweler/myjeweler/templates/employee_create.html
{% extends "base.html" %}

{% block employee_create_class %} class="active" {% endblock %}


{% block content %}
	<div>
		<form method="GET">
			{% for string in form %}
			{{ string.label }}<br>
			{{ string }}<br>
			{% endfor %}
			<input type='submit' value='submit'/>
		</form>
	</div>

{% endblock content %}

myjeweler/myjeweler/templates/employees.html
{% extends "base.html" %}

{% block employee_class %} class="active" {% endblock %}


{% block content %}

			{% for group in groups %}
			<h3><a href="{% url 'employees_group_list' group.id %}">
			 {{ forloop.counter }}. {{ group.name }}</a></h3>
			
			{% endfor %}
			{% if user.is_superuser%}
			 <p>Add group:</p>
			 <form method="GET">
			 	{{ form }}
			 </form>
			 {% endif %}

{% endblock content %}

myjeweler/myjeweler/templates/employees_item.html
{% extends "employees.html" %}

{% block employee_class %} class="active" {% endblock %}


{% block content %}


		<h3>{{ group.name }}</h3>

		{% for employee in employees %}
			<ul>
				<li><a href="{% url 'employee_one' employee.id %}">{{ forloop.counter }}. {{ employee.first_name }} {{ employee.last_name }}</a></li>
			</ul>
		{% endfor %}
{% endblock content %}

myjeweler/myjeweler/templates/employees_list.html
{% extends "base.html" %}

{% block employee_list_class %} class="active" {% endblock %}


{% block content %}


		

			{% for item in items%}
			<ul>
				<li> <h3>{{ item.id}}. {{ item.first_name }} {{ item.last_name }}</h3> {{ item.group}}
					{% if user.is_superuser %}
					<p><a href="{% url 'edit' item.id %}">Edit employee</a></p></li>				
					{% endif %}
			</ul>
			{% endfor %}

{% endblock content %}

myjeweler/myjeweler/templates/enter.html
{% extends "base.html" %}

{% block enter_class %} class="active" {% endblock %}


{% block content %}
			<form method='post' action="{% url 'login' %}">
				{% csrf_token %}
				<p><input type="text" value="login" onFocus="if(this.value=='login') this.value='';" onBlur="if(!this.value) this.value='login';"></p>
				<p><input type="password" value="password" onFocus="if(this.value=='password') this.value='';" onBlur="if(!this.value) this.value='password';"></p>
				<p><input type="submit" value="login"></p>
			</form>
{% endblock content %}		

myjeweler/myjeweler/templates/feedback.html
{% extends "base.html" %}


{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
			<div style="width: 250px; margin:0 auto">
				<h3>Обратная связь</h3>
				<form action="{% url 'feedback'%}" method="POST">
					{% csrf_token %}
					{{form}}
					<!-- <label for="id_name">Name:</label>
					<input id="id_name" type="text" name="name">
					<label for="id_email">Email:</label>
					<input id="id_email" type="text" name="email">
					<label for="id_text">Text:</label>
					<textarea id="id_text" rows="10" name="text" cols="40"></textarea> -->
					<input type='submit' value="send">
				</form>	
			</div>
{% endblock content %}

myjeweler/myjeweler/templates/index.html
{% extends "base.html" %}

{% block index_class %} class="active" {% endblock %}

{% block index_class_ %} class="active" {% endblock %}

{% block content %}
			<h3>Добро пожаловать,
				{% if user.is_authenticated%}
				 {{ user }}!
				{% else%}
				<a href="{% url 'registration_register' %}">гость</a>
				{% endif%}
			</h3>
			<p>Здесь Вы найдете то, что Вам нужно!)</p>
			<p>Пока фантазии хватило только на это.</p>
{% endblock content %}

myjeweler/myjeweler/templates/pendants.html
{% extends "base.html" %}

{% block pendants_class %} class="active" {% endblock %}

{% block pendants_class_ %} class="active" {% endblock %}


{% block content %}
			<h3><a href="">Подвесы черненные</a></h3>
			<h3><a href="">Подвесы с эмалью</a></h3>
			<h3><a href="">Крестики</a></h3>
{% endblock content %}		

myjeweler/myjeweler/templates/photo.html
{% extends "base.html" %}

{% block rings_class %} class="active" {% endblock %}

{% block rings_class_ %} class="active" {% endblock %}

{% block content %}
			<img src="/static/photo.jpg" alt="xdfhbd">
{% endblock content %}

myjeweler/myjeweler/templates/photo1.html
<html>
<head>
	<title>со вставками</title>
	<link rel="stylesheet" type="text/css" href="/static/css/all.css">
</head>
<body>
		<div class="image">
			<img src="/static/photo_rings1.jpg" alt="xdfhbd">
		</div>

</body>
</html>

myjeweler/myjeweler/templates/photo_earrings1.html
{% extends "base.html" %}

{% block earrings_class %} class="active" {% endblock %}

{% block earrings_class_ %} class="active" {% endblock %}

{% block content %}
			<img src="/static/photo_earrings1.jpg" alt="xdfhbd">
{% endblock content %}

myjeweler/myjeweler/templates/photo_rings1.html
{% extends "base.html" %}

{% block rings_class %} class="active" {% endblock %}

{% block rings_class_ %} class="active" {% endblock %}

{% block content %}
			<a href="/rings/photo_rings1/photo1/" target="blank"><img src="/static/photo_rings1.jpg" alt="xdfhbd"></a>
{% endblock content %}

myjeweler/myjeweler/templates/rings.html
{% extends "base.html" %}

{% block rings_class %} class="active" {% endblock %}

{% block rings_class_ %} class="active" {% endblock %}

{% block content %}
			<div>
				<ul>
					{% for ring in rings %}
					<li>
						<table cellpadding="3" style="border: 1px solid; width:400px; margin:0 0 10px">
							<tr>
								<td>Фото:</td>
								<td>Название:</td>
								<td>Пол:</td>
								<td>Вес:</td>
							</tr>
							<tr>	
								<td><img src="{{ ring.image.url }}" class = "image_ring"></td>
								<td>{{ring.name}}</td>
								<td>{{ring.sex }}</td>
								<td>{{ ring.weigth }}</td>
							</tr>
						</table>
					</li>
					{% endfor %}
				</ul>	
			</div>
{% endblock content %}